export const SERVER_APPLICATIONS_SLICE_NAME = 'serverApplications';

export const APPROVE_SERVER_APPLICATION_ACTION_NAME = `${SERVER_APPLICATIONS_SLICE_NAME}/approveServerApplication`;
export const REMOVE_SERVER_APPLICATION_ACTION_NAME = `${SERVER_APPLICATIONS_SLICE_NAME}/removeServerApplication`;
export const REMOVE_USER_APPLICATION_ACTION_NAME = `${SERVER_APPLICATIONS_SLICE_NAME}/removeUserApplication`;
export const GET_SERVER_APPLICATIONS_ACTION_NAME = `${SERVER_APPLICATIONS_SLICE_NAME}/getServerApplications`;
export const GET_USER_APPLICATIONS_ACTION_NAME = `${SERVER_APPLICATIONS_SLICE_NAME}/getUserApplications`;
